// Les textes du RELEVÉ DE COMPTE — le document, la feuille du téléphone et
// la section du site. Un seul nom pour l'objet, écrit ici une fois :
// « Relevé de compte » / « Account statement ». Le bilan CSV de l'Analyse
// reste ce qu'il est (un export d'écran) ; le relevé, lui, est la pièce
// qu'on remet à un comptable ou à une banque.
//
// L'anglais d'abord, écrit pour lui-même.

const en = {
  titre: "Account statement",
  // Sur la fiche d'une carte, et dans l'Analyse.
  ouvrir: "Account statement",
  explication:
    "Every money movement of the chosen period, day by day, like a bank "
    + "statement. Codes, adverts and balance checks are left out.",
  toutesLesCartes: "All my cards",
  periode: "Period",
  ceMois: "This month",
  moisDernier: "Last month",
  troisMois: "Last 3 months",
  choisirDates: "Choose the dates",
  touchezDeuxJours: "Touch the first day, then the last.",
  format: "Format",
  pdf: "PDF",
  csv: "CSV (Excel)",
  telecharger: "Download the statement",
  enCours: "Preparing…",
  impossible:
    "The statement could not be prepared. Check the connection and try again.",
  retour: "Back",
  carte: "Card",
  du: "From",
  au: "To",

  // --- Le document ------------------------------------------------------
  numeroNonRenseigne: "number not entered",
  reseau: "Network",
  titulaire: "Holder",
  libelle: "Label",
  iccid: "SIM (ICCID)",
  periodeDoc: "Period",
  editeLe: "Issued on",
  fuseau: "Time zone",
  synthese: "Summary",
  soldeOuverture: "Opening balance",
  soldeCloture: "Closing balance",
  nonConnu: "not known",
  entrees: "Money in",
  sorties: "Money out",
  frais: "Fees",
  nbOperations: "Operations",
  sensInconnu: "Direction not determined (shown, not counted)",
  sensNonDetermine: "direction not determined, not counted",
  ecart: "Difference to check",
  ecartDetail:
    "Opening + money in − money out − fees does not match the closing balance "
    + "announced by the operator.",
  incomplet:
    "INCOMPLETE STATEMENT — this card holds more messages over the period than "
    + "a statement can carry; the oldest ones are missing.",
  aucuneOperation: "No money movement over this period.",
  colDate: "Date",
  colHeure: "Time",
  colOperation: "Operation",
  colReference: "Reference",
  colDebit: "Debit",
  colCredit: "Credit",
  colFrais: "Fees",
  colSolde: "Balance after",
  suite: "continued",
  sousTotal: (entrees: string, sorties: string) => `in ${entrees} · out ${sorties}`,
  recapitulatif: "Summary by number",
  colNumero: "Number",
  pied: "Prepared from the operator's SMS; the original SMS is authoritative.",
  page: (n: number, total: number) => `page ${n}/${total}`,
  montantsEn: "Amounts in FCFA.",
  // Le CSV : des clés courtes, une ligne par information.
  csvCles: {
    titre: "statement",
    numero: "number",
    reseau: "network",
    titulaire: "holder",
    libelle: "label",
    iccid: "iccid",
    de: "from",
    a: "to",
    edite: "issued",
    ouverture: "opening_balance",
    cloture: "closing_balance",
    entrees: "money_in",
    sorties: "money_out",
    frais: "fees",
    operations: "operations",
    sensInconnu: "direction_unknown",
  },
  csvColonnes: ["date", "time", "card_number", "network", "card_iccid", "operation",
    "direction", "amount", "debit", "credit", "fees", "commission", "party", "party_number",
    "reference", "balance_after", "counted_in_totals", "message"],
  sensCsv: { in: "in", out: "out", "?": "unknown" },
  oui: "yes",
  non: "no",
};

const fr: typeof en = {
  titre: "Relevé de compte",
  ouvrir: "Relevé de compte",
  explication:
    "Tous les mouvements d’argent de la période choisie, jour par jour, comme "
    + "un relevé bancaire. Les codes, publicités et consultations de solde "
    + "n’y figurent pas.",
  toutesLesCartes: "Toutes mes cartes",
  periode: "Période",
  ceMois: "Ce mois",
  moisDernier: "Mois dernier",
  troisMois: "3 derniers mois",
  choisirDates: "Choisir les dates",
  touchezDeuxJours: "Touchez le premier jour, puis le dernier.",
  format: "Format",
  pdf: "PDF",
  csv: "CSV (Excel)",
  telecharger: "Télécharger le relevé",
  enCours: "Préparation…",
  impossible:
    "Le relevé n’a pas pu être préparé. Vérifiez la connexion, puis réessayez.",
  retour: "Retour",
  carte: "Carte",
  du: "Du",
  au: "Au",

  numeroNonRenseigne: "numéro non renseigné",
  reseau: "Réseau",
  titulaire: "Titulaire",
  libelle: "Libellé",
  iccid: "Carte SIM (ICCID)",
  periodeDoc: "Période",
  editeLe: "Édité le",
  fuseau: "Fuseau",
  synthese: "Synthèse",
  soldeOuverture: "Solde d’ouverture",
  soldeCloture: "Solde de clôture",
  nonConnu: "non connu",
  entrees: "Entrées",
  sorties: "Sorties",
  frais: "Frais",
  nbOperations: "Opérations",
  sensInconnu: "Sens non déterminé (montrées, non comptées)",
  sensNonDetermine: "sens non déterminé, non compté",
  ecart: "Écart à vérifier",
  ecartDetail:
    "Ouverture + entrées − sorties − frais ne tombe pas sur le solde de "
    + "clôture annoncé par l’opérateur.",
  incomplet:
    "RELEVÉ INCOMPLET — cette carte porte plus de messages sur la période "
    + "qu’un relevé ne peut en contenir ; les plus anciens manquent.",
  aucuneOperation: "Aucun mouvement d’argent sur cette période.",
  colDate: "Date",
  colHeure: "Heure",
  colOperation: "Opération",
  colReference: "Référence",
  colDebit: "Débit",
  colCredit: "Crédit",
  colFrais: "Frais",
  colSolde: "Solde après",
  suite: "suite",
  sousTotal: (entrees, sorties) => `entrées ${entrees} · sorties ${sorties}`,
  recapitulatif: "Récapitulatif par numéro",
  colNumero: "Numéro",
  pied: "Établi d’après les SMS de l’opérateur ; le SMS d’origine fait foi.",
  page: (n, total) => `page ${n}/${total}`,
  montantsEn: "Montants en FCFA.",
  csvCles: {
    titre: "releve",
    numero: "numero",
    reseau: "reseau",
    titulaire: "titulaire",
    libelle: "libelle",
    iccid: "iccid",
    de: "du",
    a: "au",
    edite: "edite_le",
    ouverture: "solde_ouverture",
    cloture: "solde_cloture",
    entrees: "entrees",
    sorties: "sorties",
    frais: "frais",
    operations: "operations",
    sensInconnu: "sens_inconnu",
  },
  csvColonnes: ["date", "heure", "numero_carte", "reseau", "carte_iccid", "operation",
    "sens", "montant", "debit", "credit", "frais", "commission", "tiers", "numero_tiers",
    "reference", "solde_apres", "compte_dans_totaux", "message"],
  sensCsv: { in: "entree", out: "sortie", "?": "inconnu" },
  oui: "oui",
  non: "non",
};

export const textesReleve = { en, fr } as const;
